groq:
  api_key: "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"
app:
  timezone: "Asia/Kolkata"
  interview_hours:
    start: 10
    end: 18
email:
  from_email: "recruitment@ai-recruit-assist.com"